import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import ControlBorder from '../components/controlBorder'
import PreviewBlock from '../components/previewBlock'

const Home: NextPage = () => {
  const [ propsBorder, setPropsBorder ] = useState({
    radius: {
      tl: 0,
      tr: 0,
      br: 0,
      bl: 0,
    }
  })
  useEffect(() => {
    // console.log('propsBorder ', propsBorder)
  }, [propsBorder])
  return (
    <div>
      <Head>
        <title>Border Radius Preview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PreviewBlock propsBorder={propsBorder} />
      <ControlBorder setPropsBorder={setPropsBorder} propsBorder={propsBorder} />
    </div>
  )
}

export default Home
